### ISSUE TITLE
Eliminate reflection calls in flags

### ISSUE THREAD

**Issue by davidswu** [urfave/cli#631]
Reflection should not be used to check internal field values and instead should be part of the interface. For example in the visibleFlags func
```
func visibleFlags(fl []Flag) []Flag {
	visible := []Flag{}
	for _, flag := range fl {
		if !flagValue(flag).FieldByName("Hidden").Bool() {
			visible = append(visible, flag)
		}
	}
	return visible
}
```
there is a reflection call on "Hidden" requiring each implementation to have this field. Instead this should be part of the Flag interface to make it easier for users to implement their own custom flags and extend functionality.

```
type Flag interface {
	fmt.Stringer
	// Apply Flag settings to the given flag set
	Apply(*flag.FlagSet)
	GetName() string
        Hidden() bool
}

func visibleFlags(fl []Flag) []Flag {
	visible := []Flag{}
	for _, flag := range fl {
		if !flag.Hidden() {
			visible = append(visible, flag)
		}
	}
	return visible
}
```

**Comment by jszwedko** [comment]
I think this should be fixed by #630 -- can you confirm @davidswu ?

**Comment by davidswu** [comment]
I still see the reflection calls in code [here](https://github.com/urfave/cli/pull/630/files#diff-1fdeef6cfb1d74886a385d13094d6cbcR633)

**Comment by jszwedko** [comment]
Aha, yes, I see, I missed the original intent of your report.

I agree that these should be part of the `Flag` interface, but this would, of course, be a breaking change so I hesitate to make it as part of master. I'll mark this for consideration for version 2.

**Comment by lynncyrin** [comment]
👋 v2 just hit master, so we'll need to check if this is still a valid issue 🔍

**Comment by dearchap** [comment]
@lynncyrin yes this is still present in v2. The easiest way is to add a Visible() func to Flag interface and have every flag instance implement that. If we don't want to change Flag we can add a separate interface just for Visibility and use that as a runtime type check. Let me know which you prefer. I can implement this
